// Build the Gherkin plugin for the runtime and record its hash as first-party (zarg ships it).
import { mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { bundleHash } from "@zarg/plugin/server"
import { buildPlugin } from "@zarg/plugin-sdk/tools"

const root = join(import.meta.dir, "..")
const r = await buildPlugin(join(root, "src/index.ts"))
if (!r.ok) {
  console.error(r.errors.join("\n"))
  process.exit(1)
}
mkdirSync(join(root, "dist"), { recursive: true })
writeFileSync(join(root, "dist/zarg-plugin.js"), r.bundle)
writeFileSync(join(root, "dist/zarg-plugin.json"), `${JSON.stringify(r.manifest, null, 2)}\n`)
writeFileSync(
  join(root, "../plugin/src/server/first-party-hashes.ts"),
  `// generated by packages/plugin-gherkin/scripts/build.ts — do not edit\nexport const KNOWN_FIRST_PARTY: ReadonlySet<string> = new Set(${JSON.stringify([bundleHash(r.bundle)])})\n`,
)
console.error(`gherkin plugin: ${(r.bundle.length / 1024).toFixed(0)} KiB`)
