// Build zarg's own plugins for the runtime and record every first-party hash (zarg ships them).
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { pluginHash } from "@zarg/plugin/server"
import { buildPlugin, writeDist } from "@zarg/plugin-sdk/tools"

const root = join(import.meta.dir, "..", "..")
const FIRST_PARTY = ["plugin-gherkin", "plugin-backlog", "agent-rehearse", "agent-triage", "agent-intent", "evidence-terminal", "evidence-screen"]
const only = process.argv[2]
// Bundles name their sources relative to the working directory: build from one place so the hashes do not depend on who ran it.
process.chdir(join(root, ".."))
for (const pkg of FIRST_PARTY.filter((p) => existsSync(join(root, p)) && (only === undefined || only === p))) {
  const r = await buildPlugin(join(root, pkg, "src/index.ts"))
  if (!r.ok) {
    console.error(`${pkg}:\n${r.errors.join("\n")}`)
    process.exit(1)
  }
  writeDist(join(root, pkg), r)
  console.error(`${pkg}: ${(r.bundle.length / 1024).toFixed(0)} KiB`)
}
// Every first-party bundle on disk, not only the ones built now.
const hashes = FIRST_PARTY.map((p) => join(root, p, "dist"))
  .filter((d) => existsSync(join(d, "zarg-plugin.js")))
  .map((d) => pluginHash({ bundle: readFileSync(join(d, "zarg-plugin.js"), "utf8"), manifest: JSON.parse(readFileSync(join(d, "zarg-plugin.json"), "utf8")) }))
writeFileSync(join(root, "plugin/src/server/first-party-hashes.ts"), `// generated by packages/plugin/scripts/build-plugins.ts — do not edit\nexport const KNOWN_FIRST_PARTY: ReadonlySet<string> = new Set(${JSON.stringify(hashes)})\n`)
