// Build zarg's own plugins for the runtime and record every first-party hash (zarg ships them).
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { bundleHash } from "@zarg/plugin/server"
import { buildPlugin } from "@zarg/plugin-sdk/tools"

const root = join(import.meta.dir, "..", "..")
const FIRST_PARTY = ["plugin-gherkin", "plugin-rehearse"]
const only = process.argv[2]
for (const pkg of FIRST_PARTY.filter((p) => existsSync(join(root, p)) && (only === undefined || only === p))) {
  const r = await buildPlugin(join(root, pkg, "src/index.ts"))
  if (!r.ok) {
    console.error(`${pkg}:\n${r.errors.join("\n")}`)
    process.exit(1)
  }
  mkdirSync(join(root, pkg, "dist"), { recursive: true })
  writeFileSync(join(root, pkg, "dist/zarg-plugin.js"), r.bundle)
  writeFileSync(join(root, pkg, "dist/zarg-plugin.json"), `${JSON.stringify(r.manifest, null, 2)}\n`)
  console.error(`${pkg}: ${(r.bundle.length / 1024).toFixed(0)} KiB`)
}
// Every first-party bundle on disk, not only the ones built now.
const hashes = FIRST_PARTY.map((p) => join(root, p, "dist/zarg-plugin.js")).filter(existsSync).map((f) => bundleHash(readFileSync(f, "utf8")))
writeFileSync(join(root, "plugin/src/server/first-party-hashes.ts"), `// generated by packages/plugin/scripts/build-plugins.ts — do not edit\nexport const KNOWN_FIRST_PARTY: ReadonlySet<string> = new Set(${JSON.stringify(hashes)})\n`)
