// generated by packages/plugin/scripts/build-plugins.ts — do not edit
export const KNOWN_FIRST_PARTY: ReadonlySet<string> = new Set(["831571b8213282b54f3b12481df2100b8aa149bdd06b446587819451b41d2ea4","3bebe6f202b46703de38e5836619a2057979be86d57a9a2c09f08f26db4f3073"])
