// generated by packages/plugin/scripts/build-plugins.ts — do not edit
export const KNOWN_FIRST_PARTY: ReadonlySet<string> = new Set(["1c2839c507a2820e1c50fe6c31c0a971239b2ba6e9019921b847ba573b102c03","742c5d58eefe1f9faec2df78e5002148e2c015dde696b5d8e59f568a592d6bda"])
