// generated by packages/plugin/scripts/build-plugins.ts — do not edit
export const KNOWN_FIRST_PARTY: ReadonlySet<string> = new Set(["0a19271a69aef2ce82011937807a47061aa869bd57bdf7dbb08795ad637a9a6d","9dc6ef5c397dca4e6bef076ef649a5f964ab45f2935bc402fb81db526c9c0e7d"])
